server:
    port: 9196

spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/harshalmayee/spring-cloud-config-git-server
#    boot:
#        admin:
#            client:
#                url: http://localhost:8093
    application:
        name: CONFIG-SERVER
