server:
    port: 8888
# Commented as we will be fetch global properties from git
#spring:
#    cloud:
#        config:
#            server:
#                native:
#                    search-locations: classpath:/common-config
#
#    profiles:
#        active: native




spring:
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/harshalmayee/spring-cloud-config-git-server
    boot:
        admin:
            client:
                url: http://localhost:8093
    application:
        name: Spring-Config-Server
