server:
    port: 8888
spring:
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/common-config
    profiles:
        active: native
